# 第一章python编程基础

## 1.2 python基础知识

In [125]:
print ('你好')

你好


In [126]:
1+1

2

In [127]:
1/2

0.5

In [128]:
1./2

0.5

In [129]:
x=2
x**64

18446744073709551616L

### 1.2.1 帮助

In [130]:
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__delslice__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__setslice__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [131]:
a=[1,2,3]
a.append?

In [132]:
a=[1,2,3]
help(a)

Help on list object:

class list(object)
 |  list() -> new empty list
 |  list(iterable) -> new list initialized from iterable's items
 |  
 |  Methods defined here:
 |  
 |  __add__(...)
 |      x.__add__(y) <==> x+y
 |  
 |  __contains__(...)
 |      x.__contains__(y) <==> y in x
 |  
 |  __delitem__(...)
 |      x.__delitem__(y) <==> del x[y]
 |  
 |  __delslice__(...)
 |      x.__delslice__(i, j) <==> del x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __eq__(...)
 |      x.__eq__(y) <==> x==y
 |  
 |  __ge__(...)
 |      x.__ge__(y) <==> x>=y
 |  
 |  __getattribute__(...)
 |      x.__getattribute__('name') <==> x.name
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __getslice__(...)
 |      x.__getslice__(i, j) <==> x[i:j]
 |      
 |      Use of negative indices is not supported.
 |  
 |  __gt__(...)
 |      x.__gt__(y) <==> x>y
 |  
 |  __iadd__(...)
 |      x.__iadd__(y) <==> x+=y
 |  
 |  __imul__(...)
 |      x.__imul__(y) <==

### 1.2.3 行与缩进

In [133]:
a=10;b=100;print (a+b)

110


In [134]:
def squares(n=10):
    print ("Generating squares from 1 to %d" % (n**2))
    #循环代码块
    for i in xrange(1,n+1):
        return 1**2
        #循环代码块结束
    #函数代码块结束

gen=squares()
print (gen)

Generating squares from 1 to 100
1


### 1.2.4变量与对象

In [135]:
a=10
print a

10


In [136]:
a=[1,2,3]
b=a
a.append(4)    #append是列表对象的一个方法，在对象a引用的列表中增加一个元素
b

[1, 2, 3, 4]

In [137]:
id(a),id(b),a is b  #创建了b对a的一个引用，二者id是一样的，a发生改变时b也发生改变，但如果对a重新赋值，则绑定解除

(106525384L, 106525384L, True)

In [138]:
a=[2,3,5]
b

[1, 2, 3, 4]

In [139]:
a is b

False

In [140]:
a=[1,2,['str1','str2']]

In [141]:
from copy import copy
'''
调用模块
'''
b=copy(a)
a is b

False

浅复制是指复制了对象，对象的元素被复制，但对于对象中的子元素依然是引用

In [142]:
a.append(3)  
b

[1, 2, ['str1', 'str2']]

In [143]:
a[2].append('str3')
b

[1, 2, ['str1', 'str2', 'str3']]

深复制是指完全的复制一个对象的所有元素及其子元素

In [144]:
from copy import deepcopy
a=[1,2,['str1','str2']]
b=deepcopy(a)
a is b

False

In [145]:
a.append(3)
b

[1, 2, ['str1', 'str2']]

In [146]:
a[2].append('str3')
b

[1, 2, ['str1', 'str2']]

### 1.2.5 数字与表达式

In [147]:
10,type(10)  #type是一个可以查看python对象类型的函数，返回对象类型

(10, int)

In [148]:
2**64,type(2**64)

(18446744073709551616L, long)

In [149]:
1.2345,type(1.2345)

(1.2345, float)

In [150]:
1.022e-28j,type(1.022e-28j)

(1.022e-28j, complex)

In [151]:
10/3,type(10/3)

(3.3333333333333335, float)

In [152]:
10./3,type(10./3)

(3.3333333333333335, float)

In [153]:
from __future__ import division
10/3

3.3333333333333335

In [154]:
print 1+2**3*4/5-100

-92.6


In [155]:
print 1+2**3*4/5-100

-92.6


In [156]:
a=[1,2,3]
print 10*(3 in a)   #in成员资格运算符，检查3是否在a中

10


### 1.2.7 字符串

In [157]:
a="Let's go!"
print a

Let's go!


In [158]:
b='"Hello world" printing always is the first program'
print b

"Hello world" printing always is the first program


In [159]:
"Hello," 'world!' #字符串可以自动拼接

'Hello,world!'

In [160]:
"Hello,"+'world!' #字符串可以使用“+”进行拼接

'Hello,world!'

In [161]:
"Hello,"+'world!'+'.'*10

'Hello,world!..........'

In [162]:
a='python'
a[1]

'y'

In [163]:
a[-2]

'o'

In [164]:
a[2:5] #":"前后分别表示索引的起始位置和终止位置，终止位置不包括在内

'tho'

#### 1.2.7.1 转义字符

In [165]:
ch="c:\program files\norton antivirus\officeav.dll"
print ch

c:\program files
orton antivirus\officeav.dll


In [166]:
ch1="c:\program files\\norton antivirus\officeav.dll"
print ch1

c:\program files\norton antivirus\officeav.dll


In [167]:
ch2=r"c:\program files\\norton antivirus\officeav.dll"
print ch2

c:\program files\\norton antivirus\officeav.dll


#### 1.2.7.2 字符串格式化

In [168]:
'Hello, %s' % 'world!'

'Hello, world!'

In [169]:
'Hello, %s this is %s' % ('world!','Python')

'Hello, world! this is Python'

In [170]:
'%.2f' % 3.1415926

'3.14'

In [171]:
'Age: %s. Gender: %s' %(25,'Male')

'Age: 25. Gender: Male'

In [172]:
'We must keep the growth rate at %s %%' %7

'We must keep the growth rate at 7 %'

#### 1.2.7.3 字符串的内置方法

In [173]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__getslice__',
 '__gt__',
 '__hash__',
 '__init__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_formatter_field_name_split',
 '_formatter_parser',
 'capitalize',
 'center',
 'count',
 'decode',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'index',
 'isalnum',
 'isalpha',
 'isdigit',
 'islower',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

### 1.2.8 日期和时间

In [174]:
from datetime import datetime
dt = datetime(2017,3,20,10,8,0)
dt

datetime.datetime(2017, 3, 20, 10, 8)

In [175]:
dt1=datetime(2016,3,20,10,18)
dt-dt1

datetime.timedelta(364, 85800)

In [176]:
dt.strftime('%m/%d/%Y %H:%M')

'03/20/2017 10:08'

In [177]:
dt.replace(year=2018,hour=12)

datetime.datetime(2018, 3, 20, 12, 8)

In [178]:
datetime.strptime('20170320','%Y%m%d')

datetime.datetime(2017, 3, 20, 0, 0)

In [179]:
import calendar
c=calendar.month(2017,3)
c

'     March 2017\nMo Tu We Th Fr Sa Su\n       1  2  3  4  5\n 6  7  8  9 10 11 12\n13 14 15 16 17 18 19\n20 21 22 23 24 25 26\n27 28 29 30 31\n'

In [180]:
print c

     March 2017
Mo Tu We Th Fr Sa Su
       1  2  3  4  5
 6  7  8  9 10 11 12
13 14 15 16 17 18 19
20 21 22 23 24 25 26
27 28 29 30 31



## 1.3 数据结构与序列

### 1.3.1 列表

In [181]:
name=['David Nickson','Morgan Wang','John F.Kendey','Jun Zhang']
name

['David Nickson', 'Morgan Wang', 'John F.Kendey', 'Jun Zhang']

In [182]:
list ('This is python!')

['T', 'h', 'i', 's', ' ', 'i', 's', ' ', 'p', 'y', 't', 'h', 'o', 'n', '!']

#### 1.3.1.1 列表索引和切片

In [183]:
name[1]  #索引从左到右从0开始，从右到左从-1开始

'Morgan Wang'

In [184]:
name[-1]

'Jun Zhang'

In [185]:
name[:] #通过":"隔开两个索引实现列表切片，如果提供两个索引作为边界，左闭右开

['David Nickson', 'Morgan Wang', 'John F.Kendey', 'Jun Zhang']

In [186]:
name[:2]

['David Nickson', 'Morgan Wang']

In [187]:
name[0:1]

['David Nickson']

In [188]:
name[0:]

['David Nickson', 'Morgan Wang', 'John F.Kendey', 'Jun Zhang']

In [189]:
n=[1,2,3,4,5,6,7,8,9,10]
n[0:10:1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [190]:
n[0:10:2]

[1, 3, 5, 7, 9]

In [191]:
n[::-1]  #列表元素倒序

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

#### 1.3.1.2 列表操作

"+"把不同列表合并为新列表 " * "表示重复列表元素的次数

In [192]:
n1=[1,2,3]; n2=[4,5,6]
n1+n2

[1, 2, 3, 4, 5, 6]

In [193]:
n3=list('python')
n1+n3

[1, 2, 3, 'p', 'y', 't', 'h', 'o', 'n']

In [194]:
n1*2

[1, 2, 3, 1, 2, 3]

In [195]:
"Morgan" in name  # in 成员运算符检查一个元素是否在列表中，判断列表的成员资格

False

In [196]:
"morgan wang" in name

False

In [197]:
"Morgan Wang" in name

True

In [198]:
del name[1:]    #删除元素和分片赋值
name

['David Nickson']

In [199]:
name[1:]=list('Christopher Nolan')
print name

['David Nickson', 'C', 'h', 'r', 'i', 's', 't', 'o', 'p', 'h', 'e', 'r', ' ', 'N', 'o', 'l', 'a', 'n']


#### 1.3.1.3 内置列表函数

In [200]:
n1=[1,2,3]
n2=[4,5,6]
n3=[0,1,5]
country=['China','USA','UK']
continent=['Asia','America','Euro','Asia']

In [201]:
cmp(n1,n2)

-1

In [202]:
cmp(n1,n1)

0

In [203]:
cmp(n1,n3)

1

In [204]:
len(n1)

3

In [205]:
len(country)

3

In [206]:
for i,j in enumerate(country):
    print i,j

0 China
1 USA
2 UK


In [207]:
n4=[1,3,9,2,6,8,5]
sorted(n4)
sorted(n4,reverse=True)

[9, 8, 6, 5, 3, 2, 1]

In [208]:
list (reversed(n1))

[3, 2, 1]

#### 1.3.1.4 列表方法

In [209]:
n1.append(2)  #列表末尾添加新元素
n1

[1, 2, 3, 2]

In [210]:
n1.count(2)  #统计某个元素在列表中出现的次数，并返回值

2

In [211]:
n1.extend(['w',2])  #列表末尾一次添加多个值
n1

[1, 2, 3, 2, 'w', 2]

In [212]:
n1.index(2) #列表中找出某个值的第一个匹配项的索引位置，并返回值

1

In [213]:
n1.insert(0,'wahaha') #将对象插入到列表中
n1

['wahaha', 1, 2, 3, 2, 'w', 2]

In [214]:
n1.pop()

2

### 1.3.2 元组

元组和列表一样也是一种序列，但是元组是不可变的，不能被修改，用 ， 隔开，通常用（）括起来

In [215]:
(1,2,3)

(1, 2, 3)

In [216]:
1,2,3

(1, 2, 3)

In [217]:
t=tuple('This is Python!')
t1=t+([1,2],)
print(t1)

('T', 'h', 'i', 's', ' ', 'i', 's', ' ', 'P', 'y', 't', 'h', 'o', 'n', '!', [1, 2])


In [218]:
t1[-1].append(3)
print(t1)

('T', 'h', 'i', 's', ' ', 'i', 's', ' ', 'P', 'y', 't', 'h', 'o', 'n', '!', [1, 2, 3])


In [219]:
country=('CHINA','USA','UK','JAPAN','GERMANY','FRANCE')
a1,a2,a3,a4,a5,a6=country
print(a1,a2)

('CHINA', 'USA')


### 1.3.3 字典

字典使用键值对存储，用{}将字典元素括起来，用：分割键和值并用，分隔项来定义，字典的值可以用键来引用 

In [220]:
d={'name':'WQS','Gender':'Male','Age':'20','Height':'68'}
d['name']

'WQS'

In [221]:
items=[('name','wqs'),('Gender','Male'),('Aage','20'),('Height','68')]
dict(items)    #dict函数根据序列创建字典

{'Aage': '20', 'Gender': 'Male', 'Height': '68', 'name': 'wqs'}

In [222]:
len(d)

4

In [223]:
d[1]='Hello!'
d

{1: 'Hello!', 'Age': '20', 'Gender': 'Male', 'Height': '68', 'name': 'WQS'}

In [224]:
1 in d   # 成员资格查找的是键不是值

True

In [225]:
2 in d

False

In [226]:
del d[1]
d

{'Age': '20', 'Gender': 'Male', 'Height': '68', 'name': 'WQS'}

In [227]:
d1={'name':'wqs'}
d1

{'name': 'wqs'}

In [228]:
d1.clear()  #q清除字典中的所有项，无返回值
d1

{}

In [229]:
d1={'name':'wqs'}  #浅复制
d2=d1.copy()
d2

{'name': 'wqs'}

In [230]:
d1.get('name')

'wqs'

### 1.3.4集合

In [231]:
s1=set([1,2])    #集合可以通过set、forzenset等函数创建，也可以用{}创建
s2={3,4,3}
print s1,s2    

set([1, 2]) set([3, 4])


In [232]:
set('Hello,world!')  #集合中的元素不能重复

{'!', ',', 'H', 'd', 'e', 'l', 'o', 'r', 'w'}

In [233]:
sk=set()  #创建空集合只能用set和frozenset
type(sk)

set

In [234]:
sk={}
type(sk)

dict

常用集合方法

In [235]:
s1={1,2,3,4,5  #将元素添加到集合
s1.add(5)
s1

SyntaxError: invalid syntax (<ipython-input-235-998ae3b68bbc>, line 2)

In [ ]:
s2={6,7,8}
s1.update(s2)  #用集合更新集合
s1

In [ ]:
s1.remove(1)  #从集合中删除元素，若不存在则报错
s1

In [ ]:
s1.discard(3)  #同remove 但不报错
s1

In [ ]:
s1.pop()  #删除集合中某一元素，并返回其值
s1

In [ ]:
s1.clear()

In [ ]:
s1|s2

### 1.3.5推导式

推导式是一种将for循环，if表达式以及赋值语句放到单一语句中产生序列的一种方法。主要有列表推导式、集合推导式、字典推导式

In [ ]:
string=['china','japan','usa','uk','france']  #根据一定条件成列表
upper_string=[x.upper() for x in string if len(x)>4]  #从列表中找出长度大于4的字符，并将其转为大写
upper_string 

In [ ]:
names=[['Abby','Angelia','Tammy','Barbara','Beata','Andrew','Carina'],['Hannah','Ishara','Heidi','Tiffany','Jessica','Joanna']]  
morethan2e=[n1 for n2 in names for n1 in n2 if n1.count('a')>=2]  #嵌套列表推导式将名字带有两个以上a字母的名字放入一个新列表中
morethan2e

In [ ]:
string=['china','japan','usa','uk','france','german']
string_len={len(x) for x in string if len(x)>3}  #集合推导式列表推导式的区别就是他用花括号
string_len

为字符串创建一个指向其列表位置的映射

In [ ]:
mapping=dict((val,index) for index,val in enumerate(string))
mapping

In [ ]:
mapping={val:index for index,val in enumerate(string)}
mapping

## 语句与控制流

### 1.4.1 条件语句

In [ ]:
age=input('Please input your age:')  #条件语句体是以 ： 和缩进来进行识别的
if age >= 18:
    print 'adult'
elif age>=13:
    print 'teenager'
else:
    print 'kid'

In [ ]:
a=500000
if (a==500000):print "Bingo! You've got Lotto!"  #如果满足： 后面只有一行于巨，则可以写在同一行

In [ ]:
givenname='Jing'  #三元表达式，将产生一个值的if.... else 语句写到一行或一个表达式中
'Good man!' if givenname=='Jing' else 'Can not be evaluated!'

In [ ]:
age=input('Please input your age:')
'Adult' if age>=18 else 'Kids'

In [ ]:
age=input('please input your age:')
('Kids','Adult') [age>=18] #更简洁的表示形式

### 1.4.2 循环语句

#### 1.4.2.1 while循环

In [ ]:
x=1;s=0
while x<=100:  #计算100内自然数之和
    s+=x
    x+=1
print s

如果while循环中有else语句体，则else中的语句会在循环正常执行完（非break语句终止循环）的情况下执行

In [ ]:
count=0
while count<5:
    print count,"is less than 5"
    count+=1
else:
    print count,"is not less than 5,stop!"

#### 1.4.2.2 for循环

In [ ]:
d={'name':'David','age':'35','gender':'male','department':'statistics'} #遍历字典键值对
for key in d:
    print key,'corresponds to',d[key]

In [ ]:
s=0
for i in range(1,101):  #range 函数主要用于产生一组间隔相等的整数序列，可以指定起始值、终止值以及步长
    s+=i
print s

In [ ]:
from math import sqrt
s=0
for i in range(2,100):  #xrange() 函数用法和range一样 但其生成的不是一个序列，而是一个迭代器，用于生成很大数字的序列
    k=0;j=2.
    while j<=sqrt(i):
        if i/j==int (i/j):
            k=1
            break
        j+=1
    if k==0:
        s+=i
        print i,
print '\nsum of prime numbers within 100:',s

In [ ]:
[x*x for x in range(10)]

In [ ]:
x=[]
for val in range(10):
    x.append(val**2)  #val**2 = val*val
    print val
x

#### 1.4.2.3 循环控制

In [ ]:
for a in 'This is Pyhon!':
    if a=='P':
        pass  #占位语句
        print 'passed!'
        break
    print a,

## 1.5 函数

In [ ]:
pow(2,64) #求幂内置函数

In [ ]:
pow.__doc__  #获得函数的功能说明 __doc__

In [ ]:
help(pow)

In [ ]:
pow?

def 函数名称（函数参数）
    “函数_文档字符串”
    函数体
    return [表达式]

In [ ]:
def snn(n,beg=1): 
    'calculate the sum of natural numbers within [beg,n]'
    s=0
    for i in range(beg,n+1):
        s+=i
    return s

In [ ]:
snn(100)

In [ ]:
f=snn  #函数也是一个对象，可以赋值给变量，可以直接使用被赋值的变量调用函数
f(100)

### 1.5.1 函数的参数

In [ ]:
snn(beg=1,n=100)  #命名参数，可以乱序传参

不定参数前加了 * ， 会以元组的形式存放所有未命名的参数

In [ ]:
def summation(*data):  #对任意数值求和
    s=0
    for val in data:
        s+=val
    return s

In [ ]:
summation(1,2,3)

### 1.5.2 全局变量与局部变量

In [ ]:
total=0  #函数中可以用global语句声明全局变量
def sum(paral1,paral2):
    total=paral1+paral2
    print 'Inside the function local total :',total
    return total
sum(10,20)
print 'Outside the function global total:',total

### 1.5.3 匿名函数

匿名函数仅由单条语句组成，该语句执行的结果就是返回值，省略了用def定义的函数步骤，没有名称属性

In [ ]:
def universal(some_list,func):
    return [func(x) for x in some_list]

In [ ]:
a=[1,2,3,4,5]  #对指定列表元素求平方
b=universal(a,lambda x:x**2)
b

In [ ]:
a=[1,2,3,4,5]
b=universal(a,lambda x:x**3-2*x**2-x)
b

### 1.5.4 递归和闭包

In [ ]:
def addn(n):
    if n==1:
        return 1
    return n+addn(n-1)
addn(100)

In [ ]:
def adderx(x):
    def addery(y):
        return x+y
    return addery
s=adderx(1)
print s

In [ ]:
s(100)

### 1.5.5 柯里化与反柯里化

柯里化是指一个函数在参数传递时返回另一个函数，该函数的参数就是原函数没有进行参数传递的参数

In [ ]:
def power(x,y):
    return x**y

print power(2,3)

In [ ]:
powerof2=lambda y:power(2,y)  #将power函数参数y柯里化 powerof2就是泛化出来的一个函数

In [ ]:
powerof2(5)

In [ ]:
from functools import partial
powerof_2=partial(power,2)
powerof_2(5)

In [ ]:
def power(x):  #反柯里化是柯里化的逆过程，将多个单参数函数模拟成一个多参数函数
    def p(y):
        return x**y
    return p

power(2)(5)

### 1.5.6 常用的内置函数

#### 1.5.6.1 filter函数

In [ ]:
filter(lambda x:x%2==0,range(20))

In [ ]:
print filter(lambda x:x[0]!='_',dir(list))

#### 1.5.6.2 map函数

将指定函数作用于给定序列的每个元素，并用一个列表来提供返回值

In [ ]:
map(lambda x:x%2,range(20))

In [ ]:
map(lambda x:x*2,[1,2,3,4,[5,6,7]])

In [ ]:
map(None,[1,2,3],[4,5,6])

In [ ]:
zip([1,2,3],[4,5,6])

In [ ]:
map(lambda x,y:x*y,[1,2,3],[4,5,6])

In [ ]:
map(lambda x,y:(x*y,x+y),[1,2,3],[4,5,6])

#### 1.5.6.3 reduce函数

In [ ]:
reduce (lambda x,y:x+y,[1,2,3,4])  #连续将现有结果和下一个元素作用在随后的结果上，最后将简化序列为一个单一返回值

In [ ]:
reduce(lambda x,y:x+y,[10,10],1)

In [ ]:
reduce(lambda x,y:x*y,range(1,6))

In [ ]:
reduce(lambda x,y:x+y,range(1,101))

## 1.6迭代器、生成器和装饰器

### 1.6.1 迭代器

In [ ]:
it={'a':101,'b':202,'c':303}
for keys in it:
    print keys,

先从对象it中创建一个迭代器
it_it=iter(it)
it_it
list(it)

In [ ]:
it={'a':101,'b':202,'c':303}
it_it=iter(it)
it_it.next()

In [ ]:
it_it.next()  #next 返回迭代器下一个元素  __iter__ 返回迭代器对象本身

In [ ]:
it_it.next()

In [ ]:
it_it.__iter__()

### 1.6.2 生成器

生成器以延迟的方式返回一个值序列，每返回一个值后暂停，直到下一个值被请求时再继续返回

In [ ]:
def cube(n=10):  
    print 'Generating cubes from 1 to %d' %(n**3)
    for i in xrange(1,n+1):
        yield i**3

In [ ]:
gen=cube()
gen

In [ ]:
for x in gen:
    print x,

In [ ]:
from math import sqrt
def primenumber(n):
    for i in range(2,n+1):
        k=0;j=2.
        while j<sqrt(i):
            if i/j==int(i/j):
                k=1
                break
            j+=1
        if k==0:
            yield i
            
for i in primenumber(10):
    print i,

In [ ]:
pn10=primenumber(10)
pn10.next(),pn10.next(),pn10.next()

In [ ]:
gen=(x**3 for x in xrange(100))
gen

In [ ]:
gen.next(),gen.next(),gen.next(),gen.next()

### 1.6.3 装饰器

让已有的函数在不做任何改动情况下增加特定功能

In [ ]:
import time
def timecal(func):
    def wrapper(*args,**kw):
        start=time.time()
        func(*args,**kw)
        stop=time.time()
        print 'run time is %s' %(stop-start)
    return wrapper

In [ ]:
@timecal
def snn(n,beg=1):
    'ca [beg,n]'
    s=0
    for i in range(beg,n+1):
        s+=i
    print 'sum of natural numbers within [%s,%s] is %s' %(beg,n,s)
snn(10000)

In [ ]:
def timecal(prompt):  
    def decorator(func):
        def wrapper(*args,**kw):
            start=time.time()
            func(*args,**kw)
            stop=time.time()
            print '%s run time is %s' %(prompt,(stop-start))
        return wrapper
    return decorator

In [ ]:
@timecal('Notice:')  #在定义被装饰的函数时，可在@语法糖中加入需要传递的参数
def snn(n,beg=1):
    s=0
    for i in range(beg,n+1):
        s+=i
    print 'sum of natural numbers within [%s,%s] is %s' %(beg,n,s)

In [ ]:
snn(100)

In [ ]:
timecal('Notice')(snn(100))

In [ ]:
import functools  #重新使用装饰器来装饰所定义的snn函数

def timecal(prompt):
    def decorator(func):
        @functools.wraps(func)
        def wrapper(*args,**kw):
            start=time.time()
            func(*arg,**kw)
            stop=time.time()
            print '%s run time is %s' %(prompt,(stop-start))
        return wrapper
    return decorator

In [ ]:
snn.__name__

## 1.7 类

### 1.7.1 声明类

通过class来声明，类名称一般用首字母大写的方式来表示

In [238]:
class Human(object):
    """
    也可以使用class Human:来声明经典类
    """
    phylum='chordata'
    order='primates'
    family='Human Bejing'

In [239]:
zhangsan=Human()

In [240]:
zhangsan.phylum  #获取实例的属性值

'chordata'

In [241]:
zhangsan.family='mankind'  #实例的属性值可以修改
zhangsan.family

'mankind'

In [242]:
Lisi=Human()  #对于别的类创建的实例不会有修改效果
Lisi.family

'Human Bejing'

In [243]:
Human.family='Homo'  #zhangsan的属性没有改变，因为之前将该实例的属性值进行过重新定义，不会再受到此后类属性值变化的影响
print 'zhangsan.family: %s' %zhangsan.family
print 'Lisi.family:%s' %Lisi.family
wangwu=Human()
print 'wagwu.family: %s' %wangwu.family

zhangsan.family: mankind
Lisi.family:Homo
wagwu.family: Homo


In [244]:
zhangsan.kingdom='Animalia'  #直接添加实例的属性
zhangsan.kingdom

'Animalia'

In [245]:
Human.kingdom='Animalia'  #类的属性成员直接添加
Lisi.kingdom

'Animalia'

### 1.7.3 实例方法

In [246]:
class Human(object):
    kingdom='animalia'  
    phylum='chordata'
    order='primates'
    family='Human Bejing'
    def typewrite(self):  #实例方法
        print 'This is %s typing words!' %self.family
    def add(self,n1,n2):
        n=n1+n2
        print str(n1)+'+'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.family

In [247]:
zhangsan=Human()
zhangsan.typewrite()
zhangsan.add(1,1)

This is Human Bejing typing words!
1+1=2
you see! Human Bejing can calculate!


In [248]:
class Human(object):
    domain='eukarya'  #__init()__ 在创建实例时，可以向这个实例传递参数
    def __init__ (self,kingdom='animalia',phylum='chordata',order='Primates',family='Human Beijing'):
        self.kingdom=kingdom 
        self.phylum=phylum
        self.order=order
        self.family=family
    def typewrite(self):  #实例方法
        print 'This is %s typing words!' %self.family
    def add(self,n1,n2):
        n=n1+n2
        print str(n1)+'+'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.family

zhangsan=Human()  
lisi=Human(kingdom='animal',family='Homo')
print lisi.kingdom
print lisi.family
print zhangsan.kingdom

#### 1.7.2.2 类方法

In [249]:
class Human(object):
    domain='eukarya'
    def __init__ (self,kingdom='animalia',phylum='chordata',order='Primates',family='Human Beijing'):
        self.kingdom=kingdom 
        self.phylum=phylum
        self.order=order
        self.family=family    
    def typewrite(self):  #实例方法
        print 'This is %s typing words!' %self.family
    def add(self,n1,n2):
        n=n1+n2
        print str(n1)+'+'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.family
    @classmethod
    def showclassmethodinfo(cls):
        print cls.__name__ #__name属性，其值为类名
        print dir(cls) #使用dir列示本类的所有方法

In [250]:
zhangsan=Human()
print zhangsan.showclassmethodinfo()
print Human.showclassmethodinfo()

Human
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'domain', 'showclassmethodinfo', 'typewrite']
None
Human
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'domain', 'showclassmethodinfo', 'typewrite']
None


#### 1.7.2.3 静态方法

静态方法不需要实例参数，也不需要类参数

In [251]:
class Human(object):
    domain='eukarya'
    def __init__ (self,kingdom='animalia',phylum='chordata',order='Primates',family='Human Beijing'):
        self.kingdom=kingdom 
        self.phylum=phylum
        self.order=order
        self.family=family    
    def typewrite(self):  #实例方法
        print 'This is %s typing words!' %self.family
    def add(self,n1,n2):
        n=n1+n2
        print str(n1)+'+'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.family
    @classmethod
    def showclassmethodinfo(cls):
        print cls.__name__ #__name属性，其值为类名
        print dir(cls) #使用dir列示本类的所有方法
    @staticmethod
    def showclassattributeinfo():
        print Human.__dict__

In [252]:
zhangsan=Human()
print zhangsan.showclassattributeinfo()
print zhangsan.showclassattributeinfo()

{'__module__': '__main__', 'add': <function add at 0x0000000006599BA8>, 'typewrite': <function typewrite at 0x0000000006599B38>, '__doc__': None, '__dict__': <attribute '__dict__' of 'Human' objects>, 'showclassattributeinfo': <staticmethod object at 0x00000000065FF678>, '__weakref__': <attribute '__weakref__' of 'Human' objects>, 'domain': 'eukarya', '__init__': <function __init__ at 0x0000000006599A58>, 'showclassmethodinfo': <classmethod object at 0x00000000065FF138>}
None
{'__module__': '__main__', 'add': <function add at 0x0000000006599BA8>, 'typewrite': <function typewrite at 0x0000000006599B38>, '__doc__': None, '__dict__': <attribute '__dict__' of 'Human' objects>, 'showclassattributeinfo': <staticmethod object at 0x00000000065FF678>, '__weakref__': <attribute '__weakref__' of 'Human' objects>, 'domain': 'eukarya', '__init__': <function __init__ at 0x0000000006599A58>, 'showclassmethodinfo': <classmethod object at 0x00000000065FF138>}
None


### 1.7.3 属性

#### 1.7.3.1 实例属性和类属性

In [253]:
print Human.domain
print zhangsan.domain

eukarya
eukarya


#### 1.7.3.2 私有属性和共有属性

在声明类的过程中定义属性时，带有 __前缀的属性称为私有属性，除此之外的其他属性称为公有属性

In [254]:
class Human(object):
    domain='eukarya'
    def __init__ (self,kingdom='animalia',phylum='chordata',order='Primates',family='Human Beijing'):
        self.kingdom=kingdom 
        self.phylum=phylum
        self.__order=order  #该属性为私有属性
        self.family=family    
    def typewrite(self):  #实例方法
        print 'This is %s typing words!' %self.family
    def add(self,n1,n2):
        n=n1+n2
        print str(n1)+'+'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.family
    @classmethod
    def showclassmethodinfo(cls):
        print cls.__name__ #__name属性，其值为类名
        print dir(cls) #使用dir列示本类的所有方法
    @staticmethod
    def showclassattributeinfo():
        print Human.__dict__

In [255]:
zhangsan=Human()
zhangsan.family

'Human Beijing'

In [256]:
zhangsan._Human__order  #通过实例名._类名__私有属性名 访问私有属性

'Primates'

### 1.7.4 继承

#### 1.7.4.1 隐式继承

In [257]:
class Male(Human): #隐式继承是子类从父类中完全继承了所有的成员
    pass

In [258]:
someoneismale=Male()
someoneismale.family  #隐式继承中 父类私有成员不能继承

'Human Beijing'

In [259]:
print dir(someoneismale)

['_Human__order', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'domain', 'family', 'kingdom', 'phylum', 'showclassattributeinfo', 'showclassmethodinfo', 'typewrite']


In [260]:
class Male(Human):
    def __init__(self,gender='male'):
        super(Male,self).__init__()  #super 函数的第一个参数是父类的名字
        self.gender=gender
        
    
someoneismale=Male()
someoneismale.kingdom

'animalia'

#### 1.7.4.2 显示覆盖

子类的方法名和父类的名称相同，但功能不同

In [261]:
class Male(Human):
    def __init__(self,gender='male'):
        super(Male,self).__init__()  #super 函数的第一个参数是父类的名字
        self.gender=gender
    def less(self,n1,n2):
        '''在子类中添加less方法'''
        n=n1-n2
        print str(n1)+'-'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.gender
    def add(self,n1,n2):
        '''在子类中重新定义add方法'''
        n=n1-n2
        print str(n1)+'-'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.gender

In [262]:
someoneismale=Male()
someoneismale.add(1,1)

1-1=0
you see! male can calculate!


#### 1.7.4.3 super继承

super继承 在子类中运用super函数可以达到调用子类成员名称相同的父类成员

In [263]:
class Male(Human):
    def __init__(self,gender='male'):
        super(Male,self).__init__()  #super 函数的第一个参数是父类的名字
        self.gender=gender
    def less(self,n1,n2):
        '''在子类中添加less方法'''
        n=n1-n2
        print str(n1)+'-'+str(n2)+'='+str(n)
        print 'you see! %s can calculate!' %self.gender
    def add(self,n1,n2):
        '''在子类中重新定义add方法'''
        n=n1-n2
        print str(n1)+'-'+str(n2)+'='+str(n)
        print 'you see! %s can NOT use addition!' %self.gender
    def showclassmethodinfo(self):
        print "This is Male's class method info:"
        super(Male,self).showclassmethodinfo()
        print "\nThis is Male's instance method info:"
        print dir(self)

In [264]:
someoneismale=Male()
someoneismale.showclassmethodinfo()

This is Male's class method info:
Male
['__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'domain', 'less', 'showclassattributeinfo', 'showclassmethodinfo', 'typewrite']

This is Male's instance method info:
['_Human__order', '__class__', '__delattr__', '__dict__', '__doc__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add', 'domain', 'family', 'gender', 'kingdom', 'less', 'phylum', 'showclassattributeinfo', 'showclassmethodinfo', 'typewrite']


#### 1.7.4.4 多态

In [265]:
print isinstance(someoneismale,Male)  #用isinstance函数判断实例对象是否是某种类型
print isinstance(someoneismale,Human)

True
True


In [266]:
wangwu=Human()
print isinstance(wangwu,Male)

False


In [267]:
from __future__ import division
class Female(Human):
    def __init__(self,gender='female'):
        super(Female,self).__init__()  #super 函数的第一个参数是父类的名字
        self.gender=gender
    def less(self,n1,n2):
        n=n1-n2
        print str(n1)+'-'+str(n2)+'='+str(n)
        print 'you see! %s can not use addition!' %self.gender
    def div(self,n1,n2):
        n=n1/n2
        print str(n1)+'/'+str(n2)+'='+str(n)
        print 'you see! %s can use division!' %self.gender

In [268]:
someoneisfemale=Female()
print isinstance(someoneisfemale,Female)
print isinstance(someoneisfemale,Human)
print isinstance(someoneisfemale,Male)

True
True
False


In [269]:
def addition(obj,n1,n2):
    obj.add(n1,n2)

In [270]:
addition(someoneismale,1,1)

1-1=0
you see! male can NOT use addition!


In [271]:
addition(someoneisfemale,1,1)

1+1=2
you see! Human Beijing can calculate!


In [273]:
addition(wangwu,1,1)

1+1=2
you see! Human Beijing can calculate!


In [275]:
addition(wangwu,1,1)

1+1=2
you see! Human Beijing can calculate!


In [276]:
addition(Female(),1,1)

1+1=2
you see! Human Beijing can calculate!


In [279]:
addition(Human(),1,1)

1+1=2
you see! Human Beijing can calculate!


#### 1.7.4.5 多重继承

子类不仅可以从一个父类继承，也可以从多个父类继承

In [280]:
class Somebody(Male,Female):
    pass

In [281]:
print filter(lambda x:x[0]!='_',dir(Somebody()))  #子类由父类Male和Female继承得到

['add', 'div', 'domain', 'family', 'gender', 'kingdom', 'less', 'phylum', 'showclassattributeinfo', 'showclassmethodinfo', 'typewrite']


## 1.8 模块

## 1.10 文件

In [303]:
path="D:/data/Python_data/ch1/tips.csv"
f=open(path)
type(f)

file

In [293]:
f.mode

'r'

In [294]:
f.name

'D:/data/Pythondata/ch1/tips.csv'

In [296]:
f.closed

False

In [297]:
f.read(10)

'total_bill'

In [298]:
f.read(10)

',tip,sex,s'

In [299]:
f.read(10)

'moker,day,'

In [300]:
f.seek(-30,1)
f.readlines()

['total_bill,tip,sex,smoker,day,time,size\n',
 '16.99,1.01,Female,No,Sun,Dinner,2\n',
 '10.34,1.66,Male,No,Sun,Dinner,3\n',
 '21.01,3.5,Male,No,Sun,Dinner,3\n',
 '23.68,3.31,Male,No,Sun,Dinner,2\n',
 '24.59,3.61,Female,No,Sun,Dinner,4\n',
 '25.29,4.71,Male,No,Sun,Dinner,4\n',
 '8.77,2.0,Male,No,Sun,Dinner,2\n',
 '26.88,3.12,Male,No,Sun,Dinner,4\n',
 '15.04,1.96,Male,No,Sun,Dinner,2\n',
 '14.78,3.23,Male,No,Sun,Dinner,2\n',
 '10.27,1.71,Male,No,Sun,Dinner,2\n',
 '35.26,5.0,Female,No,Sun,Dinner,4\n',
 '15.42,1.57,Male,No,Sun,Dinner,2\n',
 '18.43,3.0,Male,No,Sun,Dinner,4\n',
 '14.83,3.02,Female,No,Sun,Dinner,2\n',
 '21.58,3.92,Male,No,Sun,Dinner,2\n',
 '10.33,1.67,Female,No,Sun,Dinner,3\n',
 '16.29,3.71,Male,No,Sun,Dinner,3\n',
 '16.97,3.5,Female,No,Sun,Dinner,3\n',
 '20.65,3.35,Male,No,Sat,Dinner,3\n',
 '17.92,4.08,Male,No,Sat,Dinner,2\n',
 '20.29,2.75,Female,No,Sat,Dinner,2\n',
 '15.77,2.23,Female,No,Sat,Dinner,2\n',
 '39.42,7.58,Male,No,Sat,Dinner,4\n',
 '19.82,3.18,Male,No,Sat,Dinner,

In [304]:
f.close()
f.closed

True

# 第二章 数据预处理

## 2.1 numpy基础

numpy是python中进行数据分析最为流行的工具库之一，它能提供诸如向量、数据、矩阵等便于进行数据分析的数据结构

In [84]:
from numpy import *
%matplotlib inline
import numpy as np

In [85]:
def python_multi(n):
    a=range(n)
    b=range(n)
    c=[]
    for i in range(len(a)):
        a[i]=i**2
        b[i]=i**3
        c.append(a[i]*b[i])
    return c

def numpy_multi(n):
    c=np.arange(n)**2*np.arange(n)**3
    return c

In [86]:
%timeit python_multi(10000)  #分别使用相同的参数调用 pythonsum 和 numpysum函数 并使用魔术命令%timeit对他们的运行时间进行预算
%timeit numpy_multi(10000)

The slowest run took 4.71 times longer than the fastest. This could mean that an intermediate result is being cached.
10 loops, best of 3: 12.5 ms per loop
10000 loops, best of 3: 71.4 µs per loop


### 2.1.1 向量

向量即一维数组，用arange创建

In [87]:
v=np.arange(10) 
print v
print v.dtype
print v.shape

[0 1 2 3 4 5 6 7 8 9]
int32
(10L,)


In [88]:
vstep=np.arange(0,10,0.5) #arange 可以通过指定初始值、终止值和步长来创建一维数组
vstep

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [89]:
vstep*10

array([ 0.,  5., 10., 15., 20., 25., 30., 35., 40., 45., 50., 55., 60.,
       65., 70., 75., 80., 85., 90., 95.])

In [90]:
np.linspace(1,19,10) #初始值1 终止值19 元素个数10 的等差数列向量

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [91]:
np.linspace(1,19,10,endpoint=False) #endpoint指定是否包括终止值

array([ 1. ,  2.8,  4.6,  6.4,  8.2, 10. , 11.8, 13.6, 15.4, 17.2])

In [92]:
from math import e #导入自然数e
np.logspace(1,20,10,endpoint=False,base=e) #创建一个等比数列

array([2.71828183e+00, 1.81741454e+01, 1.21510418e+02, 8.12405825e+02,
       5.43165959e+03, 3.63155027e+04, 2.42801617e+05, 1.62334599e+06,
       1.08535199e+07, 7.25654884e+07])

In [93]:
np.zeros(20,np.int)
#array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [94]:
np.empty(20,np.int)

array([-1961601175,  1074118410,  -897940995,  1077030036, -1371696799,
        1079926954,   558101479,  1082745663,  -621099851,  1085618088,
         367545656,  1088535408,  -257755658,  1091412876,   -64388194,
        1094239537,   -54189387,  1097118609, -1048755716,  1100041483])

In [95]:
np.random.randn(10)  #randn生成正态分布随机数据

array([-0.89072521,  0.21615406,  0.31041942, -0.40006511,  0.42377769,
       -0.03590298, -0.07457439,  0.09409756, -1.33184848, -0.70044981])

In [96]:
s="Hello,python"
np.fromstring(s,dtype=np.int8)

D:\study_apps\Anaconda\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  


array([ 72, 101, 108, 108, 111,  44, 112, 121, 116, 104, 111, 110],
      dtype=int8)

In [97]:
def multiply99(i,j):
    return (i+1)*(j+1) #用fromfunction创建数组或向量 第一个参数为没个数组元素和函数名称 第二个参数指定数组的形状
np.fromfunction(multiply99,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

### 2.1.2 数组

数组 ndarray 由实际数据和描述这些数据的元数据组成

In [98]:
a=np.array([np.arange(3),np.arange(3)])
print a
print a.shape  #shape表示数组的形状
print a.ndim   #ndim表示数组的维数

[[0 1 2]
 [0 1 2]]
(2L, 3L)
2


In [99]:
np.identity(9).astype(np.int8)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [100]:
a.tolist() #也可以通过tolist方法转换为列表

[[0, 1, 2], [0, 1, 2]]

In [101]:
type(a.tolist())

list

#### 2.1.2.1 数据类型与结构数组

In [102]:
print set(np.typeDict.values())  #查看完整的ndarry数据类型

set([<type 'numpy.int8'>, <type 'numpy.uint8'>, <type 'numpy.float16'>, <type 'numpy.timedelta64'>, <type 'numpy.bool_'>, <type 'numpy.object_'>, <type 'numpy.int16'>, <type 'numpy.uint16'>, <type 'numpy.float32'>, <type 'numpy.complex64'>, <type 'numpy.string_'>, <type 'numpy.int32'>, <type 'numpy.uint32'>, <type 'numpy.float64'>, <type 'numpy.complex128'>, <type 'numpy.unicode_'>, <type 'numpy.int32'>, <type 'numpy.uint32'>, <type 'numpy.float64'>, <type 'numpy.complex128'>, <type 'numpy.void'>, <type 'numpy.int64'>, <type 'numpy.uint64'>, <type 'numpy.datetime64'>])


In [103]:
goodslist=np.dtype([('name',np.str_,50),('location',np.str_,30),('price',np.float16),('volume',np.int32)]) #用dtype函数自定义字段类型
goodslist

dtype([('name', 'S50'), ('location', 'S30'), ('price', '<f2'), ('volume', '<i4')])

In [120]:
goods=np.array([('Gree Airconditioner','JD.com',6245,1),   #构造结构数组
                ('Sony Blueray Player','Amazon.com',3210,2),
                ('Apple Macbook Pro 13','Tmall',12388,5),
                ('Iphonese','JD.com',4588,2)],dtype=goodslist)
goods

array([('Gree Airconditioner', 'JD.com',  6244., 1),
       ('Sony Blueray Player', 'Amazon.com',  3210., 2),
       ('Apple Macbook Pro 13', 'Tmall', 12380., 5),
       ('Iphonese', 'JD.com',  4588., 2)],
      dtype=[('name', 'S50'), ('location', 'S30'), ('price', '<f2'), ('volume', '<i4')])

In [121]:
'''goodsdict=np.dtype({'name':['name','location','price','volume'],
                   'formates':['s50','s30','d','i']})
goods_new=np.array([('Gree Airconditioner','JD.com',6245,1),
                    ('Sony Blueray Player','Amazon.com',3210,2),
                    ('Apple Macbook Pro 13','Tmall',12388,5),
                    ('Iphonese','JD.com',4588,2)],dtype=goodsdict)
goods_new
'''

"goodsdict=np.dtype({'name':['name','location','price','volume'],\n                   'formates':['s50','s30','d','i']})\ngoods_new=np.array([('Gree Airconditioner','JD.com',6245,1),\n                    ('Sony Blueray Player','Amazon.com',3210,2),\n                    ('Apple Macbook Pro 13','Tmall',12388,5),\n                    ('Iphonese','JD.com',4588,2)],dtype=goodsdict)\ngoods_new\n"

#### 2.1.2.2 索引与切片

1.基本索引与切片

In [122]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [123]:
print a[3]
print a[1:4]
print a[:2]
print a[-2]
print a[::-1]

7
[3 5 7]
[1 3]
17
[19 17 15 13 11  9  7  5  3  1]


In [124]:
b=np.arange(24).reshape(2,3,4) #多维数组的索引与切片类似
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [125]:
b.shape

(2L, 3L, 4L)

In [126]:
b[1,1,2]

18

In [127]:
b[0,2,...]  #选取第0层第三行的数据

array([ 8,  9, 10, 11])

In [128]:
b[0,2] 

array([ 8,  9, 10, 11])

In [129]:
b[0,...]  #多个冒号可以用...来代替

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
b[0]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [131]:
b[:,1]  #选取各层2行的数据

array([[ 4,  5,  6,  7],
       [16, 17, 18, 19]])

In [132]:
b[:,:,1]  #选取各层2列的数据

array([[ 1,  5,  9],
       [13, 17, 21]])

In [133]:
b[...,1]  #在第0层中每隔1行选取该行倒数第二个数

array([[ 1,  5,  9],
       [13, 17, 21]])

In [134]:
b[0,::2,-2]

array([ 2, 10])

In [135]:
goods['name']

array(['Gree Airconditioner', 'Sony Blueray Player',
       'Apple Macbook Pro 13', 'Iphonese'], dtype='|S50')

In [136]:
goods[3]

('Iphonese', 'JD.com', 4588., 2)

In [137]:
goods[3]['name']

'Iphonese'

In [138]:
sum(goods['volume'])

10

2.逻辑索引

逻辑索引就是布尔型索引、条件索引，可以通过制定布尔数组或者条件进行索引

In [139]:
b[b>=15]

array([15, 16, 17, 18, 19, 20, 21, 22, 23])

In [140]:
b[~(b>=15)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [141]:
b[(b>=5)&(b<=15)]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [143]:
b_bool1=np.array([False,True],dtype=bool)
b[b_bool1]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [144]:
b_bool2=np.array([False,True,True],dtype=bool)
b_bool3=np.array([False,True,True,False],dtype=bool)
b[b_bool1,b_bool2]

array([[16, 17, 18, 19],
       [20, 21, 22, 23]])

In [145]:
b[b_bool1,b_bool2,b_bool3]

array([17, 22])

3.花式索引

花式索引即利用整数数组进行索引，其可以使用指定顺序对数组提取子集

In [146]:
b[[[0],[1,2],[2,3]]]

array([ 6, 11])

In [147]:
b[np.ix_([1,0],[2,1],[0,3,2])]

array([[[20, 23, 22],
        [16, 19, 18]],

       [[ 8, 11, 10],
        [ 4,  7,  6]]])

In [149]:
b_slice=b[0,1,1:3]  #如果数组切片是一个副本不是视图，可以利用copy进行浅复制
b_copy=b[0,1,1:3].copy()
b_slice

array([5, 6])

In [150]:
b_copy

array([5, 6])

In [152]:
b_slice[1]=666
b_slice

array([  5, 666])

In [153]:
b

array([[[  0,   1,   2,   3],
        [  4,   5, 666,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

In [154]:
b_copy[1]=999
b_copy

array([  5, 999])

In [155]:
b

array([[[  0,   1,   2,   3],
        [  4,   5, 666,   7],
        [  8,   9,  10,  11]],

       [[ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23]]])

#### 2.1.2.3 数组的属性

In [156]:
ac=np.arange(12) #数组维度、大小、数据类型等
ac.shape=(2,2,3);ac

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

#### 2.1.2.4 数组排序

In [157]:
s=np.array([1,2,3,4,1,2,2,4,6,7,2,4,8,4,5])
np.sort(s) #返回排序后的数组

array([1, 1, 2, 2, 2, 2, 3, 4, 4, 4, 4, 5, 6, 7, 8])

In [158]:
np.argsort(s) #返回排序后的数组下标

array([ 0,  4,  1,  5,  6, 10,  2,  3,  7, 11, 13, 14,  8,  9, 12],
      dtype=int64)

In [159]:
s[np.argsort(-s)] 

array([8, 7, 6, 5, 4, 4, 4, 4, 3, 2, 2, 2, 2, 1, 1])

In [160]:
s.sort()
print s

[1 1 2 2 2 2 3 4 4 4 4 5 6 7 8]


In [162]:
s_r=np.array([3,23,52,34,52,3,6,645,34,7,85,23]).reshape(6,2)
s_r

array([[  3,  23],
       [ 52,  34],
       [ 52,   3],
       [  6, 645],
       [ 34,   7],
       [ 85,  23]])

In [164]:
s_r.sort(axis=1)
s_r

array([[  3,  23],
       [ 34,  52],
       [  3,  52],
       [  6, 645],
       [  7,  34],
       [ 23,  85]])

In [165]:
s_r.sort(axis=0)
s_r

array([[  3,  23],
       [  3,  34],
       [  6,  52],
       [  7,  52],
       [ 23,  85],
       [ 34, 645]])

In [166]:
s_r.sort(axis=-1)
s_r

array([[  3,  23],
       [  3,  34],
       [  6,  52],
       [  7,  52],
       [ 23,  85],
       [ 34, 645]])

In [167]:
a=[1,5,1,4,3,4,4]
b=[9,4,0,4,0,2,1]
ind=np.lexsort((b,a)) #先按a排序，再按b排序
[(a[i],b[i]) for i in ind]

[(1, 0), (1, 9), (3, 0), (4, 1), (4, 2), (4, 4), (5, 4)]

#### 2.1.2.5 数组维度

1. 展平
即把多维数组降成一维数组

In [168]:
b=np.arange(24).reshape(2,3,4)
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [169]:
b.ndim

3

In [170]:
br=np.ravel(b)
br

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [171]:
br.ndim

1

In [172]:
brsh=b.reshape(1,1,24)
brsh

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [173]:
brsh.ndim

3

In [174]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

2.维度改变

数组的reshape方法和resize方法均可以改变数组的维度和尺寸大小

In [175]:
bd=b.reshape(4,6)
bd

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [176]:
b.shape=(1,1,24)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

In [177]:
b.resize(1,1,24)
b

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
         16, 17, 18, 19, 20, 21, 22, 23]]])

3.转置

把数组的尺寸大小互换

In [179]:
b.shape=(3,4,2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

In [180]:
np.transpose(b)  #该语句等价于：b.T

array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])

In [181]:
b.T  #数组T的属性进行转置

array([[[ 0,  8, 16],
        [ 2, 10, 18],
        [ 4, 12, 20],
        [ 6, 14, 22]],

       [[ 1,  9, 17],
        [ 3, 11, 19],
        [ 5, 13, 21],
        [ 7, 15, 23]]])